<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>results.knit</title>

<script src="site_libs/header-attrs-2.18/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prediction on All-NBA teams selection</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="introduction.html">Introduction</a>
</li>
<li>
  <a href="results.html">Results</a>
</li>
<li>
  <a href="conclusion.html">Conclusion</a>
</li>
<li>
  <a href="references.html">References</a>
</li>
<li>
  <a href="https://tony-xiayi-ding.github.io">My Personal Website</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">




</div>


<div id="results" class="section level1">
<h1>Results</h1>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<p>First, I decided to further remove some variables that are not
important for our analysis, such as names, positions, teams and etc.</p>
<p>The next step was to split the whole dataset into training set and
test set. I chose to reserve 25% of the data for our test set since I
wanted to make sure that there are enough All-NBA players in the test
set for model evaluation. Subsequently, I trained the logistic
regression model along with a <strong>5-fold cross validation</strong>
and evaluated the model on the test set using a confusion matrix.</p>
<p>Below is the confusion matrix table that demonstrates the performance
of our logistic regression model on the test set. As shown below, we
obtained an overall accuracy of 98.34%, which seems to be pretty decent.
However, we also obtained a low specificity since we only predicted 44
players to make the All-NBA team out of the 66 players who actually made
the All-NBA teams in the test set.</p>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1731   22
##          1    8   44
##                                           
##                Accuracy : 0.9834          
##                  95% CI : (0.9764, 0.9888)
##     No Information Rate : 0.9634          
##     P-Value [Acc &gt; NIR] : 3.884e-07       
##                                           
##                   Kappa : 0.7373          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.01762         
##                                           
##             Sensitivity : 0.9954          
##             Specificity : 0.6667          
##          Pos Pred Value : 0.9875          
##          Neg Pred Value : 0.8462          
##               Precision : 0.9875          
##                  Recall : 0.9954          
##                      F1 : 0.9914          
##              Prevalence : 0.9634          
##          Detection Rate : 0.9590          
##    Detection Prevalence : 0.9712          
##       Balanced Accuracy : 0.8310          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>The AUC score of our model is also calculated and shown below:</p>
<pre><code>## Area under the curve: 0.831</code></pre>
<p>I also plotted the ROC curve for the logistic regression model
below:</p>
<p><img src="results_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>To determine which features of the players play important roles in
determining the All-NBA team selection, I also calculated variables’
importance and plotted the results below:</p>
<p><img src="results_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>According to the plot above, we can see that some of the features
that are more indicative of All-NBA selections are <em>Games</em>
(i.e. The number of games played in that season),
<em>ShootingPercentage</em> (i.e. Effective Field Goal Percentage; a.k.a
eFG%), and <em>BoxPlusMinus</em> (i.e. Box Plus/Minus, which is a box
score estimate of the points per 100 possessions that a player
contributed above a league-average player, translated to an average
team)<span class="math inline">\(^{1}\)</span>. From my perspective,
these top-3 most important features make sense to me in that the general
public usually regards players with high Box Plus/Minus and players who
have high field goal percentages good players; and as a result, good
players usually gets to play more games.</p>
<p>To sum up, after training a logistic regression model with 5-fold
cross validation, we obtained a model with an overall accuracy of
98.34%, and the 3 most important features indicated by this model are
<em>Games</em>, <em>ShootingPercentage</em>, and
<em>BoxPlusMinus</em>.</p>
</div>
<div id="random-forest" class="section level2">
<h2>Random Forest</h2>
<p>I also applied a <strong>5-fold cross validation</strong> to help
train the model while tuning the parameter <em>mtry</em> of my random
forest model. I tried out values from 1 to 10 for <em>mtry</em> and
reported the results in the table below (FYI: the best value used for
<em>mtry</em> is shown at the last line of the output below):</p>
<pre><code>## Random Forest 
## 
## 5415 samples
##   18 predictor
##    2 classes: &#39;0&#39;, &#39;1&#39; 
## 
## No pre-processing
## Resampling: Cross-Validated (5 fold) 
## Summary of sample sizes: 4333, 4332, 4331, 4332, 4332 
## Resampling results across tuning parameters:
## 
##   mtry  Accuracy   Kappa    
##    1    0.9787618  0.6572906
##    2    0.9795005  0.6848226
##    3    0.9789467  0.6831630
##    4    0.9789463  0.6835770
##    5    0.9795009  0.6884816
##    6    0.9795012  0.6915311
##    7    0.9796854  0.6943301
##    8    0.9795010  0.6954058
##    9    0.9789463  0.6851561
##   10    0.9791310  0.6898859
## 
## Accuracy was used to select the optimal model using the largest value.
## The final value used for the model was mtry = 7.</code></pre>
<p>Below is a visual demonstration of how the accuracy of this model
changes with the value of <em>mtry</em>:</p>
<p><img src="results_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>Below is the confusion matrix table that demonstrates the performance
of our random forest model on the test set. We obtained an overall
accuracy of 98.28%, which also seems to be pretty decent. However, we
did have a low specificity since we only predicted 44 players to make
the All-NBA team out of the 66 players who actually made the All-NBA
teams in the test set.</p>
<pre><code>## Confusion Matrix and Statistics
## 
##           Reference
## Prediction    0    1
##          0 1730   22
##          1    9   44
##                                           
##                Accuracy : 0.9828          
##                  95% CI : (0.9757, 0.9883)
##     No Information Rate : 0.9634          
##     P-Value [Acc &gt; NIR] : 8.662e-07       
##                                           
##                   Kappa : 0.7307          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.03114         
##                                           
##             Sensitivity : 0.9948          
##             Specificity : 0.6667          
##          Pos Pred Value : 0.9874          
##          Neg Pred Value : 0.8302          
##               Precision : 0.9874          
##                  Recall : 0.9948          
##                      F1 : 0.9911          
##              Prevalence : 0.9634          
##          Detection Rate : 0.9584          
##    Detection Prevalence : 0.9706          
##       Balanced Accuracy : 0.8307          
##                                           
##        &#39;Positive&#39; Class : 0               
## </code></pre>
<p>The AUC score of our model is also calculated and shown below:</p>
<pre><code>## Area under the curve: 0.8307</code></pre>
<p>I also plotted the ROC curve for the random forest model below:</p>
<p><img src="results_files/figure-html/unnamed-chunk-25-1.png" width="672" /></p>
<p>To determine which features of the players play important roles in
determining the All-NBA teams selection, I also calculated variables’
importance and plotted the results below:</p>
<p><img src="results_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<p>According to the plot above, we can see that some of the features
that are more indicative of All-NBA selections are
<em>EfficiencyRating</em> (i.e. Player Efficiency Rating, which sums up
a player’s positive accomplishments, subtracts the negative
accomplishments, and returns a per-minute rating of a player’s
performance; a.k.a PER), <em>BoxPLusMinus</em> (i.e. Box Plus/Minus,
which is a box score estimate of the points per 100 possessions that a
player contributed above a league-average player, translated to an
average team), and <em>Points</em> (i.e. The average amount of points
the player scores per game in that season)<span
class="math inline">\(^{1}\)</span>. From my perspective, these top-3
most important features also make sense to me in that the general public
usually regards players with high Box Plus/Minus, high player efficiency
rating (high PER values), and high scoring capabilities good
players.</p>
<p>To sum up, after training a random forest model with 5-fold cross
validation, we obtained a model with an overall accuracy of 98.28%, and
the 3 most important features indicated by this model are
<em>EfficiencyRating</em>, <em>BoxPlusMinus</em>, and
<em>Points</em>.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
